Added Docker compose setup (#9)
* added docker compose file

* forced a jline dumb terminal to remove warning message, added Dockerfile.dev

* solved issue with __consumer_offsets topic auto creation getting stuck in a loop due to replication factor

* changed KAFKA_ADVERTISED_LISTENERS to localhost in docker-compose file to solve issue with URLs not being pushed to the queue, other issues remain

* solved issue where Kafka consumer was consuming more than 1 record at a time but app was only processing one, artificially increasing the current offset

* reverted change to activeCrawlers start value causing bug

* updated .gitignore, added Kafka properties files

* removed redundant compose file

* fixed tests

* Docker argument passing working for basic crawler

* 98.4% test coverage

* kind of working-ish

* working-ish pt 2

* temp

* working better

* fully working ... I think

* refactor and cleanup

* update readme

diff --git a/crawl b/crawl
--- a/crawl
+++ b/crawl
@@ -1,12 +1,51 @@
 #!/bin/zsh
 
-PROJECT_NAME="simple-web-crawler-java"
-JAR_FILE="target/${PROJECT_NAME}-1.0-SNAPSHOT.jar"
+spinner() {
+    local pid=$1
+    local delay=0.1
+    local spin_chars=('|' '/' '-' '\')
 
-# Check if Maven build is needed
-if [[ ! -f "$JAR_FILE" ]]; then
-    echo "📦 Building project with Maven..."
-    mvn clean package || { echo "❌ Build failed!"; exit 1; }
+    while kill -0 "$pid" 2>/dev/null; do
+        for char in "${spin_chars[@]}"; do
+            echo -ne "\r$char"
+            sleep "$delay"
+        done
+    done
+    echo -ne "\r"
+}
+
+export COMPOSE_DISABLE_WARNINGS=1
+IMAGE_NAME="conorsheppard/simple-web-crawler-java:latest"
+ARGS="$*"
+
+START_CONTAINERS=false
+for arg in "$@"; do
+    if [[ "$arg" == "--d" || "$arg" == "--dist" || "$arg" == "--distributed" ]]; then
+        START_CONTAINERS=true
+        break
+    fi
+done
+
+if [[ "$START_CONTAINERS" == true ]]; then
+    if docker ps -q -f name=kafka-web-crawler; then
+        docker-compose down 2>/dev/null || { echo "❌ Docker Compose down failed!"; exit 1; }
+    fi
+
+    if docker ps -q -f name=redis-web-crawler; then
+        docker-compose down 2>/dev/null || { echo "❌ Docker Compose down failed!"; exit 1; }
+    fi
+
+    ARGS="${ARGS}" docker-compose up -d &
+
+    echo "Waiting for Kafka, Redis & Web Crawler containers to start..."
+    while [[ -z $(docker-compose ps -q simple-web-crawler-java) || -z $(docker ps -q -f id=$(docker-compose ps -q simple-web-crawler-java)) ]]; do
+        spinner $!
+        # sleep 1
+    done
+    
+    docker attach $(docker-compose ps -q simple-web-crawler-java)
+    docker-compose down 2>/dev/null && rm -rf kafka/data/
+else
+    # Run the crawler container without starting Kafka and Redis
+    docker run --rm -e CRAWLER_ARGS="${ARGS}" "$IMAGE_NAME" || { echo "❌ Docker run failed!"; exit 1; }
 fi
-
-java -jar "$JAR_FILE" "$@"
