working-ish pt 2

diff --git a/crawl b/crawl
--- a/crawl
+++ b/crawl
@@ -1,7 +1,8 @@
 #!/bin/zsh
 
 IMAGE_NAME="conorsheppard/simple-web-crawler-java:latest"
-
+ARGS="$*"
+echo "$ARGS"
 START_CONTAINERS=false
 for arg in "$@"; do
     if [[ "$arg" == "--d" || "$arg" == "--dist" || "$arg" == "--distributed" ]]; then
@@ -21,7 +22,7 @@ if [[ "$START_CONTAINERS" == true ]]; then
         docker-compose down || { echo "❌ Docker Compose down failed!"; exit 1; }
     fi
 
-    ARGS="https://books.toscrape.com --threads 100" docker-compose up || { echo "❌ Docker Compose up failed!"; exit 1; }
+    ARGS="$ARGS" docker-compose up || { echo "❌ Docker Compose up failed!"; exit 1; }
 else
     # Run the crawler container without starting Kafka and Redis
     echo "$@"
